project:
  type: website

website:
  title: "Stats for Scared Ecologists"
  site-url: https://statsforscaredecologists.netlify.app/
  repo-url: https://github.com/guysutton/stats_for_scared_ecologists
  open-graph: true
  twitter-card:
    creator: "@stats_ecology"
    card-style: summary_large_image
  navbar:
    background: dark
    foreground: light
    right:
      # - about.qmd
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/stats_ecology
      - icon: github
        aria-label: github
        href: https://github.com/guysutton

format:
  html:
    theme: litera
    css: styles.css

editor: visual

